INFO 2025-08-29 11:41:41,670 autoreload 3832 19188 Watching for file changes with StatReloader
INFO 2025-08-29 11:50:24,275 autoreload 3832 19188 C:\Users\Lenovo\Desktop\unityaid_platform\config\settings\base.py changed, reloading.
INFO 2025-08-29 11:50:25,693 autoreload 11124 15780 Watching for file changes with StatReloader
INFO 2025-08-29 11:51:38,909 autoreload 11124 15780 C:\Users\Lenovo\Desktop\unityaid_platform\config\settings\development.py changed, reloading.
INFO 2025-08-29 11:51:39,963 autoreload 336 17556 Watching for file changes with StatReloader
INFO 2025-08-29 11:52:14,137 autoreload 336 17556 C:\Users\Lenovo\Desktop\unityaid_platform\config\settings\development.py changed, reloading.
INFO 2025-08-29 11:52:15,245 autoreload 18888 16624 Watching for file changes with StatReloader
INFO 2025-08-29 11:52:20,358 autoreload 18888 16624 C:\Users\Lenovo\Desktop\unityaid_platform\config\settings\base.py changed, reloading.
INFO 2025-08-29 11:52:21,755 autoreload 16712 10800 Watching for file changes with StatReloader
INFO 2025-08-29 11:52:53,340 autoreload 16712 10800 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-08-29 11:52:54,422 autoreload 15508 7024 Watching for file changes with StatReloader
INFO 2025-08-29 11:53:13,507 autoreload 15508 7024 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\serializers\serializers.py changed, reloading.
INFO 2025-08-29 11:53:14,492 autoreload 8468 8524 Watching for file changes with StatReloader
INFO 2025-08-29 11:54:04,621 autoreload 8468 8524 C:\Users\Lenovo\Desktop\unityaid_platform\apps\sites\models.py changed, reloading.
INFO 2025-08-29 11:54:05,622 autoreload 15040 15896 Watching for file changes with StatReloader
INFO 2025-08-29 11:54:58,581 autoreload 16884 14096 Watching for file changes with StatReloader
INFO 2025-08-29 11:55:01,783 autoreload 15040 15896 C:\Users\Lenovo\Desktop\unityaid_platform\apps\reports\apps.py changed, reloading.
INFO 2025-08-29 11:55:01,913 autoreload 16884 14096 C:\Users\Lenovo\Desktop\unityaid_platform\apps\sites\apps.py changed, reloading.
INFO 2025-08-29 11:55:02,838 autoreload 8316 17276 Watching for file changes with StatReloader
INFO 2025-08-29 11:55:02,909 autoreload 15108 8768 Watching for file changes with StatReloader
WARNING 2025-08-29 11:55:21,502 log 8316 19280 Not Found: /
WARNING 2025-08-29 11:55:22,815 log 8316 19280 Not Found: /
WARNING 2025-08-29 11:55:23,099 log 8316 19280 Not Found: /favicon.ico
INFO 2025-08-29 16:07:51,321 autoreload 8084 5976 Watching for file changes with StatReloader
WARNING 2025-08-29 16:08:00,995 log 8084 20008 Not Found: /
INFO 2025-09-11 17:47:00,673 autoreload 17472 7360 Watching for file changes with StatReloader
INFO 2025-09-11 17:54:15,655 autoreload 18492 18872 Watching for file changes with StatReloader
INFO 2025-09-11 17:58:40,316 autoreload 17472 7360 C:\Users\Lenovo\Desktop\unityaid_platform\config\settings\development.py changed, reloading.
INFO 2025-09-11 17:58:41,190 autoreload 15352 3572 Watching for file changes with StatReloader
INFO 2025-09-11 18:00:18,384 autoreload 12028 14688 Watching for file changes with StatReloader
ERROR 2025-09-11 18:03:54,134 log 12028 18868 Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py", line 127, in register_page
    return redirect('login')
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
WARNING 2025-09-11 18:05:44,914 log 12028 18868 Not Found: /accounts/login/
ERROR 2025-09-11 18:06:29,550 log 12028 18868 Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py", line 80, in login_page
    return redirect(next_url)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
WARNING 2025-09-11 18:07:09,792 log 12028 18868 Not Found: /accounts/login/
WARNING 2025-09-11 18:43:39,900 log 12028 22308 Not Found: /favicon.ico
INFO 2025-09-11 19:08:43,308 autoreload 12028 14688 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\serializers\serializers.py changed, reloading.
INFO 2025-09-11 19:08:43,660 autoreload 15352 3572 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\serializers\serializers.py changed, reloading.
INFO 2025-09-11 19:08:44,799 autoreload 18532 17244 Watching for file changes with StatReloader
INFO 2025-09-11 19:08:45,014 autoreload 5728 9776 Watching for file changes with StatReloader
INFO 2025-09-11 19:09:04,673 autoreload 18532 17244 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\serializers\serializers.py changed, reloading.
INFO 2025-09-11 19:09:04,995 autoreload 5728 9776 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\serializers\serializers.py changed, reloading.
INFO 2025-09-11 19:09:05,910 autoreload 2960 9080 Watching for file changes with StatReloader
INFO 2025-09-11 19:09:06,199 autoreload 13204 16848 Watching for file changes with StatReloader
INFO 2025-09-11 19:09:33,707 autoreload 13204 16848 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:09:33,752 autoreload 2960 9080 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:09:34,854 autoreload 9920 13244 Watching for file changes with StatReloader
INFO 2025-09-11 19:09:34,892 autoreload 14196 22920 Watching for file changes with StatReloader
INFO 2025-09-11 19:10:02,318 autoreload 9920 13244 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:10:02,342 autoreload 14196 22920 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:10:03,511 autoreload 16532 22232 Watching for file changes with StatReloader
INFO 2025-09-11 19:10:03,512 autoreload 9552 19588 Watching for file changes with StatReloader
INFO 2025-09-11 19:11:36,553 autoreload 16532 22232 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:11:36,593 autoreload 9552 19588 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:11:37,764 autoreload 19260 3692 Watching for file changes with StatReloader
INFO 2025-09-11 19:11:37,786 autoreload 18468 17252 Watching for file changes with StatReloader
INFO 2025-09-11 19:11:48,601 autoreload 19260 3692 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:11:48,632 autoreload 18468 17252 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:11:49,922 autoreload 18904 20180 Watching for file changes with StatReloader
INFO 2025-09-11 19:11:49,954 autoreload 13232 6152 Watching for file changes with StatReloader
INFO 2025-09-11 19:12:13,218 autoreload 18904 20180 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:12:13,258 autoreload 13232 6152 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:12:14,485 autoreload 3572 13888 Watching for file changes with StatReloader
INFO 2025-09-11 19:12:14,532 autoreload 5888 21440 Watching for file changes with StatReloader
INFO 2025-09-11 19:12:35,464 autoreload 5888 21440 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:12:35,511 autoreload 3572 13888 C:\Users\Lenovo\Desktop\unityaid_platform\apps\accounts\views.py changed, reloading.
INFO 2025-09-11 19:12:36,663 autoreload 2864 3272 Watching for file changes with StatReloader
INFO 2025-09-11 19:12:36,688 autoreload 22484 11780 Watching for file changes with StatReloader
WARNING 2025-09-11 19:19:06,616 log 2864 5296 Not Found: /dashboard
WARNING 2025-09-11 19:19:12,463 log 2864 5296 Not Found: /dashboar
INFO 2025-09-11 21:51:51,217 autoreload 20296 9808 Watching for file changes with StatReloader
INFO 2025-09-11 21:56:36,622 utils 20296 17436 Verification email sent to info@aseelwomen.org
INFO 2025-09-11 22:04:54,900 autoreload 10792 13332 Watching for file changes with StatReloader
INFO 2025-09-11 22:08:16,548 utils 20296 19084 Verification email sent to info@aseelwomen.org
WARNING 2025-09-11 22:56:32,470 log 9480 19920 Unauthorized: /api/v1/sites/states/
WARNING 2025-09-11 22:59:47,372 log 9480 2648 Unauthorized: /api/v1/sites/states/
WARNING 2025-09-11 23:00:25,489 log 9480 10176 Unauthorized: /api/v1/sites/sites/map_data/
WARNING 2025-09-11 23:01:32,242 log 9480 6268 Unauthorized: /api/v1/sites/sites/map_data/
INFO 2025-09-11 23:05:01,362 autoreload 9608 15268 Watching for file changes with StatReloader
WARNING 2025-09-11 23:08:43,293 log 9480 7972 Not Found: /accounts/login/
WARNING 2025-09-11 23:08:43,615 log 9480 7972 Not Found: /favicon.ico
WARNING 2025-09-11 23:08:57,448 log 9480 7972 Not Found: /accounts/login/
WARNING 2025-09-11 23:09:11,949 log 9480 7972 Unauthorized: /api/v1/sites/states/
WARNING 2025-09-11 23:09:46,254 log 9480 9548 Unauthorized: /api/v1/sites/localities/
WARNING 2025-09-11 23:10:28,449 log 9480 9548 Unauthorized: /api/v1/sites/sites/
WARNING 2025-09-11 23:10:44,915 log 9480 9548 Unauthorized: /api/v1/sites/sites/map_data/
WARNING 2025-09-11 23:10:52,032 log 9480 9548 Unauthorized: /api/v1/sites/sites/map_data/
WARNING 2025-09-11 23:10:53,993 log 9480 9548 Unauthorized: /api/v1/sites/sites/map_data/
WARNING 2025-09-11 23:11:10,253 log 9480 9548 Unauthorized: /api/v1/sites/sites/statistics/
INFO 2025-09-12 01:22:44,167 autoreload 1284 18336 Watching for file changes with StatReloader
INFO 2025-09-12 22:52:39,233 autoreload 10332 22064 Watching for file changes with StatReloader
INFO 2025-09-12 23:40:30,042 autoreload 16120 11488 Watching for file changes with StatReloader
ERROR 2025-09-12 23:41:03,960 log 6668 18388 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 1217, in _get_serializer
    error(
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 120, in error
    GENERATOR_STATS.emit(msg, 'error')
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 89, in emit
    print(msg, file=sys.stderr)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\generators.py", line 256, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 92, in get_operation
    parameters = self._get_parameters()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 264, in _get_parameters
    **dict_helper(self._get_filter_parameters()),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 552, in _get_filter_parameters
    for filter_backend in self.get_filter_backends():
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 546, in get_filter_backends
    if not self._is_list_view():
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 135, in _is_list_view
    serializer = self.get_response_serializers()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 377, in get_response_serializers
    return self._get_serializer()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 1225, in _get_serializer
    error(
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 120, in error
    GENERATOR_STATS.emit(msg, 'error')
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 89, in emit
    print(msg, file=sys.stderr)
OSError: [Errno 22] Invalid argument
ERROR 2025-09-12 23:41:23,195 log 6668 10824 Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 1217, in _get_serializer
    error(
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 120, in error
    GENERATOR_STATS.emit(msg, 'error')
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 89, in emit
    print(msg, file=sys.stderr)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\views.py", line 84, in get
    return self._get_schema_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\views.py", line 92, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\generators.py", line 285, in get_schema
    paths=self.parse(request, public),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\generators.py", line 256, in parse
    operation = view.schema.get_operation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 92, in get_operation
    parameters = self._get_parameters()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 264, in _get_parameters
    **dict_helper(self._get_filter_parameters()),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 552, in _get_filter_parameters
    for filter_backend in self.get_filter_backends():
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 546, in get_filter_backends
    if not self._is_list_view():
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 135, in _is_list_view
    serializer = self.get_response_serializers()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 377, in get_response_serializers
    return self._get_serializer()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\openapi.py", line 1225, in _get_serializer
    error(
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 120, in error
    GENERATOR_STATS.emit(msg, 'error')
  File "C:\Users\Lenovo\Desktop\unityaid_platform\venv\Lib\site-packages\drf_spectacular\drainage.py", line 89, in emit
    print(msg, file=sys.stderr)
OSError: [Errno 22] Invalid argument
WARNING 2025-09-12 23:41:42,746 log 6668 23264 Not Found: /api/v1/reports/api/field-reports/
INFO 2025-09-12 23:42:07,516 autoreload 16120 11488 C:\Users\Lenovo\Desktop\unityaid_platform\apps\reports\urls.py changed, reloading.
INFO 2025-09-12 23:42:08,741 autoreload 4592 14056 Watching for file changes with StatReloader
WARNING 2025-09-12 23:42:23,339 log 6668 8764 Not Found: /api/v1/reports/field-reports/
INFO 2025-09-12 23:42:57,930 autoreload 4092 9260 Watching for file changes with StatReloader
WARNING 2025-09-12 23:43:11,916 log 6668 23060 Not Found: /api/v1/reports/field-reports/
WARNING 2025-09-12 23:44:46,391 log 6668 2220 Not Found: /api/v1/reports/field-reports/
INFO 2025-09-12 23:45:20,587 autoreload 23304 6356 Watching for file changes with StatReloader
WARNING 2025-09-12 23:45:37,314 log 6668 9484 Not Found: /api/v1/reports/field-reports/
INFO 2025-09-12 23:47:45,412 autoreload 23304 6356 C:\Users\Lenovo\Desktop\unityaid_platform\apps\reports\urls.py changed, reloading.
INFO 2025-09-12 23:47:46,461 autoreload 9884 13056 Watching for file changes with StatReloader
WARNING 2025-09-12 23:48:05,292 log 6668 16600 Not Found: /api/v1/reports/test/
INFO 2025-09-12 23:50:22,779 autoreload 9884 13056 C:\Users\Lenovo\Desktop\unityaid_platform\config\urls.py changed, reloading.
INFO 2025-09-12 23:50:23,867 autoreload 1220 8456 Watching for file changes with StatReloader
INFO 2025-09-12 23:50:38,719 autoreload 1220 8456 C:\Users\Lenovo\Desktop\unityaid_platform\config\urls.py changed, reloading.
INFO 2025-09-12 23:50:39,877 autoreload 8632 17160 Watching for file changes with StatReloader
WARNING 2025-09-12 23:50:52,915 log 6668 9300 Not Found: /api/v1/reports/
WARNING 2025-09-12 23:54:35,703 log 6668 23144 Not Found: /favicon.ico
WARNING 2025-09-12 23:54:44,070 log 6668 23144 Not Found: /api/v1/reports/field-reports/stats/
INFO 2025-09-13 17:10:09,405 autoreload 1952 12836 Watching for file changes with StatReloader
WARNING 2025-09-13 17:11:40,832 log 1952 5836 Unauthorized: /api/v1/assessments/assessments/
INFO 2025-09-13 18:31:43,136 autoreload 16632 18708 Watching for file changes with StatReloader
WARNING 2025-09-13 18:38:16,299 log 16632 8268 Unauthorized: /api/v1/assessments/assessments/
INFO 2025-09-13 21:00:09,356 autoreload 14436 10112 Watching for file changes with StatReloader
WARNING 2025-09-13 21:01:33,867 log 14436 2284 Not Found: /favicon.ico
ERROR 2025-09-13 21:17:01,180 kobo_service 14436 17968 Failed to fetch asset sample_form_001: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/sample_form_001/
ERROR 2025-09-13 21:17:01,180 kobo_service 14436 17968 Failed to get form URL for sample_form_001: ['Failed to fetch form details: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/sample_form_001/']
WARNING 2025-09-13 21:17:01,180 log 14436 17968 Bad Request: /api/v1/assessments/assessments/1/launch_url/
INFO 2025-09-14 00:42:55,969 autoreload 10792 13384 Watching for file changes with StatReloader
ERROR 2025-09-14 00:43:31,413 kobo_service 10792 10228 Failed to fetch asset sample_form_001: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/sample_form_001/
ERROR 2025-09-14 00:43:31,413 kobo_service 10792 10228 Failed to get form URL for sample_form_001: ['Failed to fetch form details: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/sample_form_001/']
WARNING 2025-09-14 00:43:31,413 log 10792 10228 Bad Request: /api/v1/assessments/assessments/1/launch_url/
WARNING 2025-09-14 00:44:48,893 log 10792 9004 Not Found: /accounts/login/
INFO 2025-09-14 10:49:34,367 autoreload 3548 15536 Watching for file changes with StatReloader
WARNING 2025-09-14 10:50:11,426 log 3548 17860 Unauthorized: /api/v1/assessments/assessments/
INFO 2025-09-14 10:56:29,939 autoreload 14916 15084 Watching for file changes with StatReloader
WARNING 2025-09-14 10:57:12,664 log 14916 11636 Not Found: /favicon.ico
ERROR 2025-09-14 10:58:55,404 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:58:55,406 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:58:55,409 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:09,023 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:09,023 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:09,023 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:10,217 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:10,218 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:10,220 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:11,278 kobo_service 14916 18148 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:11,279 views 14916 18148 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:11,280 log 14916 18148 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:12,544 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:12,544 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:12,544 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:14,330 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:14,331 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:14,332 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 10:59:24,016 kobo_service 14916 19592 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 10:59:24,017 views 14916 19592 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 10:59:24,020 log 14916 19592 Bad Request: /api/v1/assessments/kobo/forms/
INFO 2025-09-14 11:05:43,305 autoreload 14916 15084 C:\Users\Lenovo\Desktop\unityaid_platform\apps\assessments\views.py changed, reloading.
INFO 2025-09-14 11:05:46,645 autoreload 14136 15776 Watching for file changes with StatReloader
INFO 2025-09-14 11:06:16,050 autoreload 14136 15776 C:\Users\Lenovo\Desktop\unityaid_platform\apps\assessments\urls.py changed, reloading.
INFO 2025-09-14 11:06:19,235 autoreload 15640 8036 Watching for file changes with StatReloader
INFO 2025-09-14 11:08:43,383 autoreload 11192 7244 Watching for file changes with StatReloader
WARNING 2025-09-14 11:09:04,443 log 15640 16716 Unauthorized: /api/v1/assessments/kobo-settings/
ERROR 2025-09-14 11:12:25,854 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:25,856 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:25,858 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:12:27,425 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:27,427 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:27,429 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:12:28,232 kobo_service 15640 21244 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:28,232 views 15640 21244 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:28,234 log 15640 21244 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:12:28,991 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:28,992 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:28,996 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:12:29,641 kobo_service 15640 21244 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:29,642 views 15640 21244 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:29,645 log 15640 21244 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:12:30,434 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:12:30,435 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:12:30,435 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:13:17,605 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:13:17,606 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:13:17,609 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:13:18,829 kobo_service 15640 20868 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:13:18,830 views 15640 20868 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:13:18,834 log 15640 20868 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:13:19,064 kobo_service 15640 21244 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:13:19,066 views 15640 21244 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:13:19,066 log 15640 21244 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-14 11:13:19,809 kobo_service 15640 8148 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-14 11:13:19,809 views 15640 8148 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-14 11:13:19,809 log 15640 8148 Bad Request: /api/v1/assessments/kobo/forms/
INFO 2025-09-15 15:31:42,683 autoreload 10072 9232 Watching for file changes with StatReloader
WARNING 2025-09-15 15:31:52,949 log 10072 6108 Unauthorized: /api/v1/integrations/api/data-integration/test_connections/
INFO 2025-09-15 15:33:19,652 autoreload 10072 9232 C:\Users\Lenovo\Desktop\unityaid_platform\apps\integrations\views.py changed, reloading.
INFO 2025-09-15 15:33:21,458 autoreload 11476 12408 Watching for file changes with StatReloader
INFO 2025-09-15 15:33:35,833 autoreload 11476 12408 C:\Users\Lenovo\Desktop\unityaid_platform\apps\integrations\views.py changed, reloading.
INFO 2025-09-15 15:33:37,820 autoreload 16984 7504 Watching for file changes with StatReloader
INFO 2025-09-15 15:33:51,073 autoreload 16984 7504 C:\Users\Lenovo\Desktop\unityaid_platform\apps\integrations\views.py changed, reloading.
INFO 2025-09-15 15:33:52,825 autoreload 6372 12468 Watching for file changes with StatReloader
ERROR 2025-09-15 15:35:00,647 hdx_service 6372 13340 Failed to fetch population data: 403 Client Error: Forbidden for url: https://hapi.humdata.org/api/v1/coordination-context/population?location_code=SDN&admin_level=1&reference_period_start=2023-04-15&reference_period_end=2023-05-15&output_format=json
ERROR 2025-09-15 15:35:00,647 hdx_service 6372 13340 Failed to fetch comprehensive Sudan data: ['Failed to fetch population data: 403 Client Error: Forbidden for url: https://hapi.humdata.org/api/v1/coordination-context/population?location_code=SDN&admin_level=1&reference_period_start=2023-04-15&reference_period_end=2023-05-15&output_format=json']
ERROR 2025-09-15 15:35:00,657 views 6372 13340 HDX sync failed: ["Failed to fetch comprehensive data: ['Failed to fetch population data: 403 Client Error: Forbidden for url: https://hapi.humdata.org/api/v1/coordination-context/population?location_code=SDN&admin_level=1&reference_period_start=2023-04-15&reference_period_end=2023-05-15&output_format=json']"]
ERROR 2025-09-15 15:35:00,670 log 6372 13340 Internal Server Error: /api/v1/integrations/api/data-integration/sync_hdx_data/
INFO 2025-09-15 17:23:26,594 autoreload 12984 4584 Watching for file changes with StatReloader
WARNING 2025-09-15 17:25:50,384 log 12984 10760 Forbidden: /api/v1/assessments/assessments/3/send-to-sites/
ERROR 2025-09-15 17:27:25,758 kobo_service 12984 10524 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-15 17:27:25,760 views 12984 10524 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-15 17:27:25,762 log 12984 10524 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-15 17:27:26,983 kobo_service 12984 10760 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-15 17:27:26,985 views 12984 10760 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-15 17:27:26,988 log 12984 10760 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-15 17:27:27,393 kobo_service 12984 10524 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-15 17:27:27,393 views 12984 10524 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-15 17:27:27,393 log 12984 10524 Bad Request: /api/v1/assessments/kobo/forms/
ERROR 2025-09-15 17:27:28,059 kobo_service 12984 612 Failed to fetch Kobo assets: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/
ERROR 2025-09-15 17:27:28,060 views 12984 612 Failed to fetch Kobo forms for user 2: ['Failed to fetch forms from Kobo: 401 Client Error: Unauthorized for url: https://kf.kobotoolbox.org/api/v2/assets/']
WARNING 2025-09-15 17:27:28,062 log 12984 612 Bad Request: /api/v1/assessments/kobo/forms/
